# Official Vite+ toolchain exceptions: https://viteplus.dev/guide/migrate
overrides:
  "vite@*": npm:@voidzero-dev/vite-plus-core@1.1.0
  "vitest@*": 5.0.3

allowBuilds:
  esbuild: true
  msgpackr-extract: false
