packages:
  - app/*
  - packages/*
  - tests/*
  - examples/*

catalog:
  alchemy: 2.0.0-beta.77
  "@comark/react": 0.6.2
  shiki: 4.4.3
  "@tailwindcss/vite": ^4.3.3
  vite-plus: 0.3.1
  effect: 4.0.0-rc.112
  "@effect/platform-browser": 4.0.0-rc.112
  "@effect/platform-node-shared": 4.0.0-rc.112
  react: 19.3.0-canary-1d34f91d-20260909
  react-dom: 19.3.0-canary-1d34f91d-20260909
  "@types/react": 19.3.0
  "@types/react-dom": 19.3.0
  "@vitejs/plugin-rsc": 0.5.34
  wrangler: 4.131.0

minimumReleaseAgeExclude:
  - "@cloudflare/vite-plugin@1.54.7"
  - miniflare@5.20260910.0-alpha
  - wrangler@4.131.0

overrides:
  effect: 4.0.0-rc.112
  "@effect/platform-node": 4.0.0-rc.112
  "@effect/platform-node-shared": 4.0.0-rc.112
  "@effect/platform-browser": 4.0.0-rc.112
  "@effect/vitest": 4.0.0-rc.112
  "@effect/sql-d1": 4.0.0-rc.112
  "@effect/sql-sqlite-do": 4.0.0-rc.112
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vitest: 4.1.11
  react: 19.3.0-canary-1d34f91d-20260909
  react-dom: 19.3.0-canary-1d34f91d-20260909

allowBuilds:
  msgpackr-extract: false
  esbuild: true
  workerd: true
