import type { DocPage } from "../types";

export const englishArticleCatalog = [
  {
    slug: "/",
    title: "Effront",
    description:
      "A React meta-framework built on Effect, with server-rendered pages, typed services, and Server Functions.",
    section: "Getting started",
    headings: [
      { id: "boundaries", title: "Get a page on screen" },
      { id: "overview", title: "Add data and user actions" },
      { id: "next", title: "Choose your next guide" },
    ],
    source: "/index",
  },
  {
    slug: "/guide/getting-started",
    title: "Getting started",
    description: "Display Hello, world with your first Effront application.",
    section: "Getting started",
    headings: [
      { id: "setup", title: "Run the sample" },
      { id: "application", title: "Explore the sample" },
      { id: "run", title: "Change the heading" },
    ],
    source: "/guide/getting-started",
  },
  {
    slug: "/platforms",
    title: "Deployment platforms",
    description: "Set up development and production environments for your deployment target.",
    section: "Platforms",
    headings: [{ id: "support", title: "Choose your hosting model" }],
    source: "/platforms",
  },
  {
    slug: "/platforms/cloudflare",
    title: "Cloudflare Workers",
    description:
      "A guide to setting up development and production environments for Cloudflare Workers.",
    section: "Platforms",
    headings: [
      { id: "setup", title: "Run the example" },
      { id: "vite", title: "Find the Worker configuration" },
      { id: "local", title: "Run the built Worker with Wrangler" },
      { id: "context", title: "Read Worker bindings and request context" },
      { id: "alchemy", title: "Manage resources with Alchemy" },
    ],
    source: "/platforms/cloudflare",
  },
  {
    slug: "/platforms/node",
    title: "Node.js",
    description:
      "Run the Node.js example in development, then build and start its production server.",
    section: "Platforms",
    headings: [
      { id: "setup", title: "Run the example" },
      { id: "entries", title: "Find the application and server files" },
      { id: "assets", title: "Check the production build locally" },
      { id: "node", title: "Start the Node.js server" },
    ],
    source: "/platforms/node",
  },
  {
    slug: "/platforms/bun",
    title: "Bun",
    description: "Run the Bun example in development, then build and start its production server.",
    section: "Platforms",
    headings: [
      { id: "setup", title: "Run the example" },
      { id: "entries", title: "Find the application and server files" },
      { id: "assets", title: "Check the production build locally" },
      { id: "bun", title: "Start the Bun server" },
    ],
    source: "/platforms/bun",
  },
  {
    slug: "/platforms/alchemy",
    title: "Alchemy and Cloudflare",
    description: "A guide to setting up a Cloudflare Workers development environment with Alchemy.",
    section: "Platforms",
    headings: [
      { id: "setup", title: "Prepare the example" },
      { id: "worker", title: "Find the application and resource definitions" },
      { id: "stack", title: "Start development" },
      { id: "capabilities", title: "Add resources when needed" },
    ],
    source: "/platforms/alchemy",
  },
  {
    slug: "/guide/routes",
    title: "Pages, layouts, and routes",
    description: "A guide to building pages and shared layouts and connecting them to URLs.",
    section: "Guides",
    headings: [
      { id: "layouts", title: "Define the shared Layout" },
      { id: "pages", title: "Define the Page content" },
      { id: "routes", title: "Connect the Layout and Page with Routes" },
      { id: "application", title: "Run the complete application entry" },
      { id: "matching", title: "Read path parameters" },
      { id: "mount", title: "Add a section layout and loading UI" },
    ],
    source: "/guide/routes",
  },
  {
    slug: "/guide/components",
    title: "Server and Client Components",
    description:
      "Keep data access on the server while adding reusable UI and interactive controls.",
    section: "Guides",
    headings: [
      { id: "boundary", title: "Choose a component for the task" },
      { id: "server", title: "Reuse server-rendered UI" },
      { id: "client-boundary", title: "Add an interactive control" },
    ],
    source: "/guide/components",
  },
  {
    slug: "/guide/server-functions",
    title: "Server Functions",
    description:
      "Handle form submissions and client calls with server-side validation and responses your UI can use.",
    section: "Guides",
    headings: [
      { id: "identity", title: "Share the application definition" },
      { id: "forms", title: "Submit a form directly" },
      { id: "application", title: "Render and submit the form" },
      { id: "state", title: "Add form state with useActionState" },
      { id: "input", title: "Accept an object argument" },
      { id: "refresh", title: "Handle updates" },
      { id: "errors", title: "Handle failures" },
    ],
    source: "/guide/server-functions",
  },
  {
    slug: "/guide/effect",
    title: "Application services",
    description: "A guide to structuring application logic and dependencies with Effect services.",
    section: "Guides",
    headings: [
      { id: "service", title: "Use a service in a Page" },
      { id: "lifetime", title: "Choose the service scope" },
      { id: "missing-services", title: "Fix missing-service errors" },
    ],
    source: "/guide/effect",
  },
  {
    slug: "/guide/middleware",
    title: "Middleware",
    description:
      "A guide to sharing request handling, such as authentication, across pages and Server Functions.",
    section: "Guides",
    headings: [
      { id: "reach", title: "Choose the request scope" },
      { id: "view", title: "Provide a request service" },
      { id: "routes", title: "Apply the service to a Page" },
      { id: "order", title: "Return an early response" },
      { id: "actions", title: "Apply checks to a Server Function" },
    ],
    source: "/guide/middleware",
  },
  {
    slug: "/guide/http",
    title: "HTTP endpoints",
    description: "A guide to adding HTTP APIs alongside your application pages.",
    section: "Guides",
    headings: [
      { id: "router", title: "Define a JSON endpoint" },
      { id: "services", title: "Register the route and its service" },
      { id: "boundary", title: "Keep resources request-local" },
      { id: "global", title: "Add a shared response header" },
    ],
    source: "/guide/http",
  },
  {
    slug: "/guide/markdown",
    title: "Writing pages in Markdown",
    description: "A guide to publishing Markdown content as Effront pages.",
    section: "Guides",
    headings: [
      { id: "setup", title: "Add an article" },
      { id: "collection", title: "Load the collection" },
      { id: "render", title: "Render the article at its URL" },
      { id: "authoring", title: "Customize parsing or rendering" },
    ],
    source: "/guide/markdown",
  },
  {
    slug: "/guide/styling",
    title: "Styling with Tailwind",
    description: "A guide to styling Effront applications with Tailwind CSS.",
    section: "Guides",
    headings: [
      { id: "setup", title: "Add Tailwind utilities" },
      { id: "stylesheet", title: "Define a theme in a stylesheet" },
      { id: "scope", title: "Add an optional Tailwind plugin" },
    ],
    source: "/guide/styling",
  },
  {
    slug: "/advanced/client-navigation",
    title: "Client navigation",
    description: "Use links, preserve shared Layout state, and configure Page animations.",
    section: "Guides",
    headings: [
      { id: "native-navigation", title: "Follow ordinary links" },
      { id: "transition-scope", title: "Turn off a Page's animation" },
      { id: "global-config", title: "Turn off animations across the application" },
      { id: "commit-and-stream", title: "Keep loading UI visible until content arrives" },
      { id: "history-cache", title: "Back, Forward, and reload" },
    ],
    source: "/advanced/client-navigation",
  },
  {
    slug: "/advanced/server-function-execution-and-refresh",
    title: "Server Function results and refresh",
    description: "How Server Function results and page updates relate to each other.",
    section: "Guides",
    headings: [
      { id: "execution", title: "One call returns a result and a refreshed page" },
      { id: "result-and-refresh", title: "The result can arrive before the view" },
      { id: "concurrency", title: "Refresh ordering is not write ordering" },
    ],
    source: "/advanced/server-function-execution-and-refresh",
  },
  {
    slug: "/best-practices/authentication-and-authorization",
    title: "Authentication and authorization",
    description:
      "Apply authentication and authorization to Routes and Server Functions with a shared middleware policy.",
    section: "Best practices",
    headings: [
      { id: "entry-points", title: "Apply checks at each entry point" },
      { id: "shared-policy", title: "Share one policy across both registrations" },
      { id: "authorization", title: "Authorize each operation" },
    ],
    source: "/best-practices/authentication-and-authorization",
  },
  {
    slug: "/advanced/request-runtime-and-lifetimes",
    title: "Manage service lifetimes",
    description:
      "Choose owners for request, shared, and background-work resources, with cleanup timed to their use.",
    section: "Best practices",
    headings: [
      { id: "resource-design", title: "Choose the resource owner" },
      { id: "request-layer", title: "Acquire request resources in the application Layer" },
      { id: "response-lifetime", title: "Keep resources alive through the response body" },
    ],
    source: "/advanced/request-runtime-and-lifetimes",
  },
  {
    slug: "/best-practices/testing",
    title: "Testing your application",
    description:
      "Runnable Playwright examples for testing Route, Page, Layout, and Server Function behavior.",
    section: "Best practices",
    headings: [
      { id: "tools", title: "Use the runnable example" },
      { id: "routes", title: "Test Route responses" },
      { id: "pages", title: "Test Page output and hydration" },
      { id: "layouts", title: "Test Layout retention across navigation" },
      { id: "server-functions", title: "Test a Server Function through its client" },
    ],
    source: "/best-practices/testing",
  },
  {
    slug: "/api-reference",
    title: "API reference",
    description:
      "Find public import paths, application factory APIs, and compatible dependency versions.",
    section: "API reference",
    headings: [
      { id: "exports", title: "Public API map" },
      { id: "index", title: "Application factory index" },
      { id: "versions", title: "Dependency matrix" },
    ],
    source: "/api-reference",
  },
  {
    slug: "/api-reference/application",
    title: "Application",
    description: "API reference for defining an Effront application and its services.",
    section: "API reference",
    headings: [
      { id: "example", title: "Application definition example" },
      { id: "identity", title: "Application.effront" },
      { id: "make", title: "EFFRONT.make" },
      { id: "middleware", title: "EFFRONT.withMiddleware" },
    ],
    source: "/api-reference/application",
  },
  {
    slug: "/api-reference/components",
    title: "Component, Page, Layout, and Loading",
    description: "API reference for rendering pages, components, layouts, and loading states.",
    section: "API reference",
    headings: [
      { id: "render", title: "Rendering factories" },
      { id: "loading", title: "Layout and Loading" },
      { id: "params", title: "Page params" },
      { id: "view-transition", title: "PageViewTransition" },
    ],
    source: "/api-reference/components",
  },
  {
    slug: "/api-reference/routing",
    title: "Routes and Middleware",
    description: "API reference for route definitions and request middleware.",
    section: "API reference",
    headings: [
      { id: "routes", title: "Routes" },
      { id: "paths", title: "Route paths" },
      { id: "middleware", title: "Middleware" },
    ],
    source: "/api-reference/routing",
  },
  {
    slug: "/api-reference/server-functions",
    title: "ServerFn",
    description: "API reference for defining server-side functions callable from React.",
    section: "API reference",
    headings: [
      { id: "make", title: "ServerFn.make" },
      { id: "arguments", title: "Argument shapes" },
      { id: "execution", title: "Execution constraints" },
      { id: "request-protocol", title: "Request protocol" },
    ],
    source: "/api-reference/server-functions",
  },
  {
    slug: "/api-reference/workers",
    title: "Fetch handlers and Workers context",
    description: "API reference for Fetch handlers and access to Workers request context.",
    section: "API reference",
    headings: [
      { id: "fetch", title: "createFetchHandler" },
      { id: "readers", title: "Core context readers" },
      { id: "cloudflare", title: "Cloudflare context readers" },
      { id: "context", title: "WorkersRequestContext" },
    ],
    source: "/api-reference/workers",
  },
  {
    slug: "/api-reference/vite",
    title: "Vite and Cloudflare plugins",
    description: "Configuration reference for Effront’s Vite and Cloudflare Workers integrations.",
    section: "API reference",
    headings: [
      { id: "effront", title: "effront" },
      { id: "configuration", title: "EffrontViteOptions" },
      { id: "cloudflare", title: "effrontCloudflare" },
    ],
    source: "/api-reference/vite",
  },
  {
    slug: "/api-reference/http",
    title: "Effect HTTP handlers",
    description: "API reference for connecting Effront applications to Effect HTTP servers.",
    section: "API reference",
    headings: [
      { id: "fetch", title: "HTTP boundaries" },
      { id: "handler", title: "toHttpEffect" },
      { id: "capture", title: "makeHttpEffect" },
    ],
    source: "/api-reference/http",
  },
  {
    slug: "/api-reference/server",
    title: "Node.js and Bun server APIs",
    description: "API reference for running Effront applications on Node.js and Bun.",
    section: "API reference",
    headings: [
      { id: "vite", title: "effrontServer" },
      { id: "serve", title: "serve" },
      { id: "assets", title: "withAssets" },
    ],
    source: "/api-reference/server",
  },
  {
    slug: "/api-reference/markdown",
    title: "Markdown API",
    description: "API reference for Markdown collections and parsing.",
    section: "API reference",
    headings: [
      { id: "collection", title: "createMarkdownCollection" },
      { id: "parse", title: "parseMarkdown" },
      { id: "references", title: "Links, assets, and MarkdownError" },
    ],
    source: "/api-reference/markdown",
  },
  {
    slug: "/api-reference/alchemy",
    title: "Alchemy API",
    description: "API reference for connecting Effront applications to Alchemy Workers.",
    section: "API reference",
    headings: [
      { id: "http", title: "HTTP handlers" },
      { id: "vite", title: "effrontAlchemy" },
    ],
    source: "/api-reference/alchemy",
  },
  {
    slug: "/api-reference/tailwind",
    title: "Tailwind API",
    description: "Configuration reference for Effront’s Tailwind CSS integration.",
    section: "API reference",
    headings: [
      { id: "plugin", title: "effrontTailwind" },
      { id: "stylesheet", title: "stylesheet" },
    ],
    source: "/api-reference/tailwind",
  },
] as const satisfies readonly (Omit<DocPage, "content"> & { readonly source: string })[];
