import type { DocPage } from "./types";

// Stable routes and heading IDs are independent of Markdown file naming.
export const articleCatalog = [
  {
    slug: "/",
    title: "Effront",
    description:
      "サーバーでのページ描画、型付きサービス、Server Functions を備えた、Effect ベースの React メタフレームワーク。",
    section: "Getting started",
    headings: [
      { id: "boundaries", title: "ページを表示する" },
      { id: "overview", title: "データとユーザー操作を扱う" },
      { id: "next", title: "次のガイドを選ぶ" },
    ],
    source: "/index",
  },
  {
    slug: "/guide/getting-started",
    title: "はじめる",
    description: "Hello, world を表示する、はじめての Effront アプリケーション。",
    section: "Getting started",
    headings: [
      { id: "setup", title: "サンプルを起動する" },
      { id: "application", title: "サンプルの構成を見る" },
      { id: "run", title: "表示内容を変える" },
    ],
    source: "/guide/getting-started",
  },
  {
    slug: "/platforms",
    title: "デプロイ先",
    description: "デプロイ先に合わせて、開発環境と本番環境をセットアップします。",
    section: "Platforms",
    headings: [{ id: "support", title: "ホスティング方式を選ぶ" }],
    source: "/platforms",
  },
  {
    slug: "/platforms/cloudflare",
    title: "Cloudflare Workers",
    description: "Cloudflare Workers 向けの開発環境・本番環境セットアップガイド。",
    section: "Platforms",
    headings: [
      { id: "setup", title: "サンプルを起動する" },
      { id: "vite", title: "Worker の設定を確認する" },
      { id: "local", title: "ビルド済みの Worker をプレビューする" },
      { id: "context", title: "アプリケーション変数を変更する" },
      { id: "alchemy", title: "Alchemy でリソースを管理する" },
    ],
    source: "/platforms/cloudflare",
  },
  {
    slug: "/platforms/node",
    title: "Node.js",
    description:
      "Node.js サンプルを開発モードで動かし、ビルドのプレビューと本番サーバーの起動を確認します。",
    section: "Platforms",
    headings: [
      { id: "setup", title: "サンプルを起動する" },
      { id: "entries", title: "アプリケーションとサーバーのファイルを確認する" },
      { id: "assets", title: "本番ビルドをローカルで確認する" },
      { id: "node", title: "Node.js サーバーを起動する" },
    ],
    source: "/platforms/node",
  },
  {
    slug: "/platforms/bun",
    title: "Bun",
    description:
      "Bun サンプルを開発モードで動かし、ビルドのプレビューと本番サーバーの起動を確認します。",
    section: "Platforms",
    headings: [
      { id: "setup", title: "サンプルを起動する" },
      { id: "entries", title: "アプリケーションとサーバーのファイルを確認する" },
      { id: "assets", title: "本番ビルドをローカルで確認する" },
      { id: "bun", title: "Bun サーバーを起動する" },
    ],
    source: "/platforms/bun",
  },
  {
    slug: "/platforms/alchemy",
    title: "Alchemy と Cloudflare",
    description: "Alchemy を使った Cloudflare Workers 向けの開発環境セットアップガイド。",
    section: "Platforms",
    headings: [
      { id: "setup", title: "サンプルを準備する" },
      { id: "worker", title: "アプリケーションとリソースの定義を確認する" },
      { id: "stack", title: "開発サーバーを起動する" },
      { id: "capabilities", title: "必要に応じてリソースを追加する" },
    ],
    source: "/platforms/alchemy",
  },
  {
    slug: "/guide/routes",
    title: "ページ、レイアウト、ルート",
    description: "ページと共通のレイアウトを作り、URL に対応付けるためのガイド。",
    section: "Guides",
    headings: [
      { id: "layouts", title: "共通の Layout を定義する" },
      { id: "pages", title: "Page の内容を定義する" },
      { id: "routes", title: "Routes で Layout と Page を接続する" },
      { id: "application", title: "エントリー全体を組み合わせて動かす" },
      { id: "matching", title: "URL パラメーターを受け取る" },
      { id: "mount", title: "セクションの Layout と読み込み表示を追加する" },
    ],
    source: "/guide/routes",
  },
  {
    slug: "/guide/components",
    title: "Server Component と Client Component",
    description:
      "データへのアクセスをサーバー側に保ちながら、再利用できる UI と操作用の部品を追加します。",
    section: "Guides",
    headings: [
      { id: "boundary", title: "処理に合うコンポーネントを選ぶ" },
      { id: "server", title: "サーバー側の表示を再利用する" },
      { id: "client-boundary", title: "操作できる UI を加える" },
    ],
    source: "/guide/components",
  },
  {
    slug: "/guide/server-functions",
    title: "Server Function",
    description:
      "フォームの送信やクライアントからの呼び出しに対し、サーバー側で入力を検証し、UI で使える応答を返します。",
    section: "Guides",
    headings: [
      { id: "identity", title: "アプリケーション定義を共有する" },
      { id: "state", title: "フォームの状態を返す" },
      { id: "application", title: "フォームを表示して送信する" },
      { id: "forms", title: "状態を返さずに送信する" },
      { id: "input", title: "オブジェクトを引数に取る" },
      { id: "refresh", title: "更新と失敗を扱う" },
    ],
    source: "/guide/server-functions",
  },
  {
    slug: "/guide/effect",
    title: "アプリケーションサービス",
    description: "Effect のサービスで、アプリケーションの処理と依存関係を構成するためのガイド。",
    section: "Guides",
    headings: [
      { id: "service", title: "Page でサービスを使う" },
      { id: "lifetime", title: "サービスのスコープを選ぶ" },
      { id: "missing-services", title: "サービス不足の型エラーを直す" },
    ],
    source: "/guide/effect",
  },
  {
    slug: "/guide/middleware",
    title: "Middleware",
    description: "認証などのリクエスト処理を、ページや Server Function で共通化するためのガイド。",
    section: "Guides",
    headings: [
      { id: "reach", title: "適用するリクエストを選ぶ" },
      { id: "view", title: "リクエストのサービスを提供する" },
      { id: "routes", title: "Page にサービスを適用する" },
      { id: "order", title: "後続の処理を止めて応答する" },
      { id: "actions", title: "Server Function にチェックを適用する" },
    ],
    source: "/guide/middleware",
  },
  {
    slug: "/guide/http",
    title: "HTTP エンドポイント",
    description: "アプリケーションのページと併せて HTTP API を提供するためのガイド。",
    section: "Guides",
    headings: [
      { id: "router", title: "JSON エンドポイントを定義する" },
      { id: "services", title: "ルートとサービスを登録する" },
      { id: "boundary", title: "リソースをリクエスト内で使う" },
      { id: "global", title: "共通のレスポンスヘッダーを追加する" },
    ],
    source: "/guide/http",
  },
  {
    slug: "/guide/markdown",
    title: "Markdown でページを書く",
    description: "Markdown コンテンツを Effront のページとして公開するためのガイド。",
    section: "Guides",
    headings: [
      { id: "setup", title: "記事を追加する" },
      { id: "collection", title: "コレクションを読み込む" },
      { id: "render", title: "記事を URL で表示する" },
      { id: "authoring", title: "解析や表示を変更する" },
    ],
    source: "/guide/markdown",
  },
  {
    slug: "/guide/styling",
    title: "Tailwind によるスタイリング",
    description: "Tailwind CSS を使った Effront アプリケーションのスタイリングガイド。",
    section: "Guides",
    headings: [
      { id: "setup", title: "Tailwind のユーティリティを使う" },
      { id: "stylesheet", title: "スタイルシートでテーマを定義する" },
      { id: "scope", title: "必要に応じて Tailwind プラグインを追加する" },
    ],
    source: "/guide/styling",
  },
  {
    slug: "/advanced",
    title: "実行時の動作",
    description: "ページ更新、画面遷移、リソースの生存期間に関する Effront の動作を解説します。",
    section: "Guides",
    headings: [{ id: "chapters", title: "実行時の契約" }],
    source: "/advanced",
    group: "実行時の契約",
  },
  {
    slug: "/advanced/request-runtime-and-lifetimes",
    title: "リクエストとリソースの生存期間",
    description:
      "リクエストの処理からレスポンスの配信まで、アプリケーションサービスの生存期間を解説します。",
    section: "Guides",
    headings: [
      { id: "response-lifetime", title: "Response の処理はハンドラーの後も続く" },
      { id: "request-layer", title: "アプリケーションのサービスはリクエストごとに構築される" },
      { id: "render-scope", title: "遅れて始まるレンダーも同じサービスを使う" },
      { id: "resource-design", title: "リクエスト所有とホスト所有のリソース" },
    ],
    source: "/advanced/request-runtime-and-lifetimes",
    group: "実行時の契約",
  },
  {
    slug: "/advanced/client-navigation",
    title: "クライアントナビゲーション",
    description: "ページ遷移に伴う、共通 UI の状態・読み込み・ブラウザー履歴の動作を解説します。",
    section: "Guides",
    headings: [
      { id: "native-navigation", title: "ページ間で保持される状態" },
      { id: "transition-scope", title: "Page のアニメーションと共有 Layout" },
      { id: "commit-and-stream", title: "画面表示、URL、ストリームの完了" },
      { id: "history-cache", title: "履歴の再利用とドキュメントの読み込み" },
    ],
    source: "/advanced/client-navigation",
    group: "実行時の契約",
  },
  {
    slug: "/advanced/server-function-execution-and-refresh",
    title: "Server Function の結果と画面更新",
    description: "Server Function の実行結果と画面更新の関係を解説します。",
    section: "Guides",
    headings: [
      { id: "execution", title: "一度の呼び出しで結果と更新後のページを返す" },
      { id: "input-boundary", title: "入力の検証と認可は別の役割" },
      { id: "result-and-refresh", title: "画面より先に関数の結果が届く" },
      { id: "concurrency", title: "画面更新の順序と書き込み順序は別" },
    ],
    source: "/advanced/server-function-execution-and-refresh",
    group: "実行時の契約",
  },
  {
    slug: "/best-practices/testing",
    title: "アプリケーションのテスト",
    description: "アプリケーションの動作と業務ルールを検証するための、テストの設計・実行指針。",
    section: "Best practices",
    headings: [
      { id: "pages", title: "保存した変更をブラウザーで確かめる" },
      { id: "services", title: "Server Function が呼び出す業務ルールをテストする" },
      { id: "production", title: "公開用の成果物を検証する" },
      { id: "tools", title: "データを分離し、起動を自動化する" },
    ],
    source: "/best-practices/testing",
  },
  {
    slug: "/api-reference",
    title: "API リファレンス",
    description:
      "公開 import パス、アプリケーションファクトリーの API、互換性のある依存バージョンを調べます。",
    section: "API reference",
    headings: [
      { id: "exports", title: "公開 API の一覧" },
      { id: "index", title: "アプリケーションファクトリーの索引" },
      { id: "versions", title: "依存バージョン一覧" },
    ],
    source: "/api-reference",
  },
  {
    slug: "/api-reference/application",
    title: "Application",
    description: "Effront アプリケーションとサービスの定義に使う API のリファレンス。",
    section: "API reference",
    headings: [
      { id: "example", title: "アプリケーション定義の例" },
      { id: "identity", title: "Application.effront" },
      { id: "make", title: "EFFRONT.make" },
      { id: "middleware", title: "EFFRONT.withMiddleware" },
    ],
    source: "/api-reference/application",
  },
  {
    slug: "/api-reference/components",
    title: "Component・Page・Layout・Loading",
    description:
      "ページ、コンポーネント、レイアウト、読み込み中の表示を定義する API のリファレンス。",
    section: "API reference",
    headings: [
      { id: "render", title: "描画ファクトリー" },
      { id: "loading", title: "Layout と Loading" },
      { id: "params", title: "Page params" },
      { id: "view-transition", title: "PageViewTransition" },
    ],
    source: "/api-reference/components",
  },
  {
    slug: "/api-reference/routing",
    title: "Routes と Middleware",
    description: "ルートの定義とリクエストのミドルウェアに関する API リファレンス。",
    section: "API reference",
    headings: [
      { id: "routes", title: "Routes" },
      { id: "paths", title: "ルートパス" },
      { id: "middleware", title: "Middleware" },
    ],
    source: "/api-reference/routing",
  },
  {
    slug: "/api-reference/server-functions",
    title: "ServerFn",
    description: "React から呼び出せるサーバー側の関数を定義する API のリファレンス。",
    section: "API reference",
    headings: [
      { id: "make", title: "ServerFn.make" },
      { id: "arguments", title: "引数の形式" },
      { id: "execution", title: "実行上の制約" },
    ],
    source: "/api-reference/server-functions",
  },
  {
    slug: "/api-reference/workers",
    title: "Fetch ハンドラーと Workers コンテキスト",
    description: "Fetch ハンドラーと Workers のリクエストコンテキストを扱う API のリファレンス。",
    section: "API reference",
    headings: [
      { id: "fetch", title: "createFetchHandler" },
      { id: "readers", title: "コアの Context 読み取り関数" },
      { id: "cloudflare", title: "Cloudflare の Context 読み取り関数" },
      { id: "context", title: "WorkersRequestContext" },
    ],
    source: "/api-reference/workers",
  },
  {
    slug: "/api-reference/vite",
    title: "Vite と Cloudflare のプラグイン",
    description: "Effront の Vite 連携と Cloudflare Workers 連携に関する設定リファレンス。",
    section: "API reference",
    headings: [
      { id: "effront", title: "effront" },
      { id: "configuration", title: "EffrontViteOptions" },
      { id: "cloudflare", title: "effrontCloudflare" },
    ],
    source: "/api-reference/vite",
  },
  {
    slug: "/api-reference/http",
    title: "Effect HTTP ハンドラー",
    description: "Effront アプリケーションを Effect HTTP サーバーに接続する API のリファレンス。",
    section: "API reference",
    headings: [
      { id: "fetch", title: "HTTP の接続 API" },
      { id: "handler", title: "toHttpEffect" },
      { id: "capture", title: "makeHttpEffect" },
    ],
    source: "/api-reference/http",
  },
  {
    slug: "/api-reference/server",
    title: "Node.js と Bun のサーバー API",
    description: "Node.js と Bun で Effront アプリケーションを実行する API のリファレンス。",
    section: "API reference",
    headings: [
      { id: "vite", title: "effrontServer" },
      { id: "serve", title: "serve" },
      { id: "assets", title: "withAssets" },
    ],
    source: "/api-reference/server",
  },
  {
    slug: "/api-reference/markdown",
    title: "Markdown API",
    description: "Markdown コレクションとパーサーの API リファレンス。",
    section: "API reference",
    headings: [
      { id: "collection", title: "createMarkdownCollection" },
      { id: "parse", title: "parseMarkdown" },
      { id: "references", title: "リンク、アセット、MarkdownError" },
    ],
    source: "/api-reference/markdown",
  },
  {
    slug: "/api-reference/alchemy",
    title: "Alchemy API",
    description: "Effront アプリケーションを Alchemy の Worker に接続する API のリファレンス。",
    section: "API reference",
    headings: [
      { id: "http", title: "HTTP ハンドラー" },
      { id: "vite", title: "effrontAlchemy" },
    ],
    source: "/api-reference/alchemy",
  },
  {
    slug: "/api-reference/tailwind",
    title: "Tailwind API",
    description: "Effront の Tailwind CSS 連携に関する設定リファレンス。",
    section: "API reference",
    headings: [
      { id: "plugin", title: "effrontTailwind" },
      { id: "stylesheet", title: "stylesheet" },
    ],
    source: "/api-reference/tailwind",
  },
] as const satisfies readonly (Omit<DocPage, "content"> & { readonly source: string })[];
